### ISSUE TITLE
Game screen rapidly flashes different colors when opening menu

### ISSUE THREAD

**Issue by bleakassassin** [libretro/bsnes#4] opened 2019-09-21 04:19 UTC
Opening the RetroArch menu when running the bsnes HD core causes the current game's screen to exhibit an erratic strobe light effect. None of the core options seem to be causing this, as I couldn't cause the effect to change when editing any of them. This happens with both my personal RA setup and a new install.

I'd have to think that this is a big issue because it could be a health concern for people susceptible to seizures.

**Comment by rtretiakov** [comment] 2019-09-21 13:48
It has been suggested that this issue is caused by RetroArch's handling of RGB1555 pixels:
https://www.reddit.com/r/emulation/comments/d6tel1/bsnes_v110_released_byuu/f0wed6v/?utm_source=share&utm_medium=web2x
This is not an issue with this specific core. It happens with any core that uses RGB1555, so I will close this issue. I recommend opening this on the RetroArch issues page.
We are hoping to change the pixel format used by bsnes in the future, and that would also resolve the problem in the case of bsnes at least. That might be done upstream or it might be done in this port. That question is still open.

**Closed as completed by rtretiakov** 2019-09-21 13:48 UTC

**Comment by Awakened0** [comment] 2019-10-01 00:28
The beetle-ngp core had the same issue a while back: https://github.com/libretro/beetle-ngp-libretro/issues/54

No idea if the same fix could apply here, but figured I'd mention it in case it might help.

**Comment by bleakassassin** [comment] 2019-10-07 22:37
This issue is still occurring with the latest version of bsnes.

I think someone other than me should open this issue up in the RetroArch issues page. I'm not well-educated enough on color space to properly convey the problem at hand.
