### ISSUE TITLE
Latest bsnes core no longer works/New update crash retroarch on loading any game/

### ISSUE THREAD

**Issue by wem2977** [libretro/bsnes#48] opened 2021-01-12 10:16 UTC
Runing window 10 version of retroach 1.9
loading any snes game will boot retroach back to desktop
Also loading just the core will crash retroarch too

bsnes core no longer works

**Comment by Ryunam** [comment] 2021-01-31 10:48
Not sure if you are the same user who reported a similar issue recently on reddit, but I can confirm that this is not happening on my end with the latest core downloaded from the buildbot. I'm on Windows 10 x64, using the glcore video driver, and the bsnes core is working as normal.

Can you provide some more details, namely which video driver you are using? Is this happening with the latest RA nightly?

**Comment by wem2977** [comment] 2021-01-31 21:13
Hi

I'm not the one on Reddit who reported the issue but I am having the same
issue. I'm using the retroarch latest nightly build on windows 10 x64 and
have tried different graphic drivers including glcore. However i did not
download the bsnes core from the official buildbot , I got it from the
retroarch download core tab.

If you need any more information please let me know.

**Comment by Jamirus238** [comment] 2021-02-01 17:37
If have similar problems (maybe not quite the same) problems in Windows 7, the core won't load, this also happened under Linux for me the day before.

Win log says: unknown error 3221225501
Log Windows says: Exception Code=0xc000001d  flags=0x0 at 0x000000001388B614

**Comment by Tatsuya79** [comment] 2021-02-01 20:58
It's crashing for me too.
Then I compiled it myself and it works fine.

Got this warning during compilation if that's relevant:
```make
In file included from ../nall/string.hpp:17,
                 from ../nall/chrono.hpp:4,
                 from ./emulator/emulator.hpp:8,
                 from ./processor/processor.hpp:3,
                 from processor/spc700/spc700.cpp:1:
In function 'T* nall::memory::copy(void*, nall::uint, const void*, nall::uint) [with T = unsigned char]',
    inlined from 'T* nall::memory::copy(void*, const void*, nall::uint) [with T = unsigned char]' at ../nall/memory.hpp:107:17,
    inlined from 'void nall::string::_allocate()' at ../nall/string/allocator/adaptive.hpp:100:15,
    inlined from 'nall::string::type& nall::string::reserve(nall::uint)' at ../nall/string/allocator/adaptive.hpp:51:14,
    inlined from 'nall::string::type& nall::string::resize(nall::uint)' at ../nall/string/allocator/adaptive.hpp:63:15,
    inlined from 'nall::string nall::hex(uintmax, long int, char)' at ../nall/string/format.hpp:100:21,
    inlined from 'Processor::SPC700::disassemble(uint16, bool)::<lambda()>' at processor/spc700/disassembler.cpp:17:60:
../nall/memory.hpp:102:19: warning: 'void* __builtin_memcpy(void*, const void*, long long unsigned int)' writing 24 bytes into a region of size 6 [-Wstringop-overflow=]
  102 |   while(l--) *t++ = *s++;
      |              ~~~~~^~~~~~
../nall/memory.hpp: In lambda function:
../nall/memory.hpp:46:20: note: at offset 0 to an object with size 6 allocated by 'malloc' here
   46 |   return (T*)malloc(size * sizeof(T));
      |              ~~~~~~^~~~~~~~~~~~~~~~~~
```

**Comment by hizzlekizzle** [comment] 2021-02-01 21:09
So, something up with the buildbot builds, but obscure enough that it's not affecting everyone....

**Comment by detectorcaleta1** [comment] 2021-02-05 03:55
Hello everyone, 

I am using Windows 10 Pro 2004 x64 and the core Bsnes 115 works perfect in my end as well, I use the video driver Vulkan. This core perfectly boots up all SNES, MSU1s, Satellaview and Super Game Boy ROMs. I updated Retroarch to the latest Nightly version 02/04/2021.

Thank you, have a nice day guys.

**Comment by mr-falafel** [comment] 2021-02-11 23:14
Same issue. Downloaded the BSNES core from retroarch's built-in core downloader. Retroarch crashes when attempting to load any rom and loading the core by itself, from Load Core, either boots back to Retroarch with no core loaded or crashes. Tried with glcore, gl and vulkan, with identical results.

Windows 10 Pro x64
Retroarch 1.9.0, from the official installer.

**Comment by hugopachecoaz** [comment] 2021-03-06 14:20
> Same issue. Downloaded the BSNES core from retroarch's built-in core downloader. Retroarch crashes when attempting to load any rom and loading the core by itself, from Load Core, either boots back to Retroarch with no core loaded or crashes. Tried with glcore, gl and vulkan, with identical results.
> 
> Windows 10 Pro x64
> Retroarch 1.9.0, from the official installer.

I am facing exactly the same thing.

**Comment by mr-falafel** [comment] 2021-03-07 02:29
Just updated all cores and tried it on my laptop and it's working, now.
I'll try on my desktop computer, tomorrow.
Both are Windows 10 Pro x64 so I expect it to work there, too. I'll post my results.

**Comment by hugopachecoaz** [comment] 2021-03-07 13:01
> Just updated all cores and tried it on my laptop and it's working, now.
> I'll try on my desktop computer, tomorrow.
> Both are Windows 10 Pro x64 so I expect it to work there, too. I'll post my results.

I tried again and the problem persists in bsnes and retroarch 1.9.0 (tested on windows 7 and windows 10). Bsnes Mercury runs perfectly.

**Comment by mr-falafel** [comment] 2021-03-07 20:22
Just tried on my desktop and "Core Failed to Load"... Windows, Retroarch and BSNES are all the same on both machines. That is to say they're both running Windows 10 Pro x64 with Retroarch 1.9.0, installed from the official installer, and BSNES installed and fully updated from within retorarch's online updater. My laptop runs an intel CPU, with onboard graphics, while my desktop has an AMD CPU and GPU. Since running vulken, gl and glcore all gives the same results, I'm thinking it's not the GPU but that's only a guess.

**Comment by mr-falafel** [comment] 2021-03-07 20:24
@hugopachecoaz Do you happen to be using an AMD CPU or GPU?

**Comment by hugopachecoaz** [comment] 2021-03-07 21:13
> @hugopachecoaz Do you happen to be using an AMD CPU or GPU?

On the windows 7 desktop I am using an amd fx 6300 and on the windows 10 desktop an Intel g4560, both with nvidia gpus.

**Comment by mr-falafel** [comment] 2021-03-08 14:12
I am also using an older AMD CPU from around the same time period. The AMD A10-6800K. I wonder if that could be the cause. As mentioned, my laptop has a weaker but slightly newer intel CPU and can run the core just fine.

**Comment by hugopachecoaz** [comment] 2021-03-09 15:41
> I am also using an older AMD CPU from around the same time period. The AMD A10-6800K. I wonder if that could be the cause. As mentioned, my laptop has a weaker but slightly newer intel CPU and can run the core just fine.

I tested it now on a Windows 10 notebook with an old i5 4200U cpu and it worked. On the other PCs that I tested (AMD and Intel), all the BSNES variants available on Retroarch work, except for this standard BSNES version.

**Comment by mr-falafel** [comment] 2021-03-09 16:28
@hugopachecoaz All the other BSNES cores work for me, too.

**Comment by Awakened0** [comment] 2021-03-15 05:43
I get "Core failed to load" with the latest Win64 build on the buildbot too. Using Windows 10 with an i5 2500K + GTX 970. If I build myself from the new [bsnes-libretro repo](https://github.com/libretro/bsnes-libretro), it works fine. The .dll is only 3.26MB compared to the 23.1MB one on the buildbot too, which is nice.

**Comment by nativepapaya** [comment] 2021-03-29 20:13
Latest version also fails for me. I am using a 4930k + 3090. Sounds older CPUs might have an issue.

**Comment by jdgleaver** [comment] 2021-03-30 09:35
The core was being built incorrectly. Could someone with Windows please check that it works after this is merged? https://github.com/libretro/bsnes/pull/57 (I only have Linux...)

**Comment by hugopachecoaz** [comment] 2021-03-30 10:23
I updated and tested it, but the problem still persists. The error message "Failed to load libretro core" appears every time I try to load a rom, sometimes RetroArch even crashes.

**Comment by jdgleaver** [comment] 2021-03-30 10:28
The changes haven't been merged yet - the core file on the buildbot is still the old version...

**Comment by hugopachecoaz** [comment] 2021-03-30 10:51
> The changes haven't been merged yet - the core file on the buildbot is still the old version...

Sorry, I did not know. I'll wait a few days and test again... Thanks!

**Comment by mr-falafel** [comment] 2021-03-30 20:44
> 
> 
> The core was being built incorrectly. Could someone with Windows please check that it works after this is merged? #57 (I only have Linux...)

Great to hear. I'll test it and report as soon as it's on the buildbot.

**Comment by hugopachecoaz** [comment] 2021-04-02 18:42
Updated yesterday and now the core works perfectly.

**Comment by wem2977** [comment] 2021-04-02 21:01
The core is still the old version 115 the latest version is 117, they just
rolled it back. Nothing been fixed yet.

**Comment by hizzlekizzle** [comment] 2021-04-03 19:05
It should be up to date now, even if the version number wasn't ticked up: https://github.com/libretro/bsnes/commits/master

**Comment by mr-falafel** [comment] 2021-04-05 14:49
Can confirm. It's working perfectly for me, now. Thanks everyone for your ongoing hard work on this awesome project.

**Closed as completed** 2021-04-05 15:25 UTC
